# Generated by Django 4.1.7 on 2023-06-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10, verbose_name='Status')),
                ('description', models.TextField(max_length=150, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10, verbose_name='Status')),
                ('is_type_a_invoice', models.BooleanField(verbose_name='Is Type A Invoice')),
                ('description', models.TextField(max_length=150, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Subcategory Name')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10, verbose_name='Status')),
                ('is_type_a_invoice', models.BooleanField(verbose_name='Is Type A Invoice')),
                ('description', models.TextField(max_length=150, verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('product_image', models.ImageField(upload_to=None, verbose_name='Product Image')),
                ('re_order_mark', models.PositiveIntegerField(verbose_name='Re Order Mark (Pieces)')),
                ('is_apply_ml_quantity', models.BooleanField(verbose_name='Is Apply ML Quantity')),
                ('ml_quantity', models.PositiveIntegerField(verbose_name='ML Quantity')),
                ('is_apply_weight', models.BooleanField(verbose_name='Is Apply Weight (OZ)')),
                ('weight', models.FloatField(verbose_name='Weight (Oz)')),
                ('commission_code', models.DecimalField(choices=[('0.00', '0.00%'), ('0.01', '0.01%'), ('1.00', '1.00%')], decimal_places=2, max_digits=5, verbose_name='Commission Code')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock(Pieces)')),
                ('srp', models.FloatField(verbose_name='SRP(Suggested Retail Price)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10, verbose_name='Status')),
                ('is_type_a_invoice', models.BooleanField(verbose_name='Is Type A Invoice')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
