# Generated by Django 4.1.7 on 2023-06-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_brand_alter_product_commission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_base_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Retail Base Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_min_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Retail Min Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_base_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Wholesale Base Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_min_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Wholesale Min Price'),
        ),
    ]
