# Generated by Django 4.1.7 on 2023-06-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_cost_price_product_retail_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(default=0, verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_base_price',
            field=models.FloatField(default=0, verbose_name='Retail Base Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_min_price',
            field=models.FloatField(default=0, verbose_name='Retail Min Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_base_price',
            field=models.FloatField(default=0, verbose_name='Wholesale Base Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_min_price',
            field=models.FloatField(default=0, verbose_name='Wholesale Min Price'),
        ),
    ]
