# Generated by Django 4.1.7 on 2023-06-26 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companyusers_user'),
        ('vendors', '0004_vendor_company'),
        ('product', '0006_alter_brand_status_alter_category_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_company', to='company.company', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_company', to='company.company', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='box',
            field=models.BooleanField(default=1, verbose_name='Box'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='box_piece',
            field=models.IntegerField(default=1, verbose_name='Pieces in Box'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='case',
            field=models.BooleanField(default=1, verbose_name='Case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='case_piece',
            field=models.IntegerField(default=1, verbose_name='Pieces in Case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_company', to='company.company', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prefered_vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor', to='vendors.vendor', verbose_name='Prefered Vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_company', to='company.company', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product', verbose_name='Product Image'),
        ),
    ]
