# Generated by Django 4.1.7 on 2023-06-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_brand_company_category_company_product_box_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="box_piece",
            field=models.IntegerField(default=0, verbose_name="Pieces in Box"),
        ),
        migrations.AlterField(
            model_name="product",
            name="case_piece",
            field=models.IntegerField(default=0, verbose_name="Pieces in Case"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                upload_to="product-images", verbose_name="Product Image"
            ),
        ),
    ]
