# Generated by Django 4.1.7 on 2023-06-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_warehouse_address1_remove_warehouse_address2_and_more'),
        ('product', '0008_alter_product_box_piece_alter_product_case_piece_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.CreateModel(
            name='WarehouseProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock(Pieces)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='product.product', verbose_name='Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock', to='company.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
