# Generated by Django 4.1.7 on 2023-07-03 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_created_at_alter_company_updated_at_and_more'),
        ('product', '0010_alter_brand_created_at_alter_brand_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProductStockHisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('before_stock', models.PositiveIntegerField(default=0, verbose_name='Stock(Pieces)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock(Pieces)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_history', to='product.product', verbose_name='Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock_history', to='company.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
