# Generated by Django 4.1.7 on 2023-07-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_created_at_alter_company_updated_at_and_more'),
        ('product', '0011_warehouseproductstockhisory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WarehouseProductStockHisory',
            new_name='WarehouseProductStockHistory',
        ),
    ]
