# Generated by Django 4.1.7 on 2023-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_warehouseproductstockhistory_before_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductstockhistory',
            name='affected_stock',
            field=models.IntegerField(default=0, verbose_name='Affected Stock(Pieces)'),
        ),
        migrations.AddField(
            model_name='warehouseproductstockhistory',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
    ]
