# Generated by Django 4.1.7 on 2023-07-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_warehouseproductstockhistory_before_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(
                blank=True, max_length=150, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, max_length=150, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_type_a_invoice",
            field=models.BooleanField(default=False, verbose_name="Is Type A Invoice"),
        ),
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="box",
            field=models.BooleanField(default=False, verbose_name="Box"),
        ),
        migrations.AlterField(
            model_name="product",
            name="case",
            field=models.BooleanField(default=False, verbose_name="Case"),
        ),
        migrations.AlterField(
            model_name="product",
            name="commission_code",
            field=models.FloatField(
                choices=[(0.0, "0.00%"), (0.01, "0.01%"), (1.0, "1.00%")],
                default=0.0,
                verbose_name="Commission Code",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_apply_ml_quantity",
            field=models.BooleanField(
                default=False, verbose_name="Is Apply ML Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_apply_weight",
            field=models.BooleanField(
                default=False, verbose_name="Is Apply Weight (OZ)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_type_a_invoice",
            field=models.BooleanField(default=False, verbose_name="Is Type A Invoice"),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default=False,
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="description",
            field=models.TextField(
                blank=True, max_length=150, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="is_type_a_invoice",
            field=models.BooleanField(default=False, verbose_name="Is Type A Invoice"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
