# Generated by Django 4.1.7 on 2023-07-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_alter_brand_description_alter_brand_status_and_more"),
        ("product", "0014_warehouseproductstockhistory_affected_stock_and_more"),
    ]

    operations = []
