# Generated by Django 4.1.7 on 2023-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_merge_20230704_0944"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cost_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="retail_base_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="retail_min_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="wholesale_base_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="wholesale_min_price",
        ),
        migrations.AddField(
            model_name="product",
            name="box_base_price",
            field=models.FloatField(default=0.0, verbose_name="Box Base Price"),
        ),
        migrations.AddField(
            model_name="product",
            name="box_cost_price",
            field=models.FloatField(default=0.0, verbose_name="Box Cost Price"),
        ),
        migrations.AddField(
            model_name="product",
            name="box_retail_base_price",
            field=models.FloatField(default=0.0, verbose_name="Box Retail Base Price"),
        ),
        migrations.AddField(
            model_name="product",
            name="box_retail_min_price",
            field=models.FloatField(default=0.0, verbose_name="Box Retail Min Price"),
        ),
        migrations.AddField(
            model_name="product",
            name="box_upc",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Box UPC"),
        ),
        migrations.AddField(
            model_name="product",
            name="box_wholesale_base_price",
            field=models.FloatField(
                default=0.0, verbose_name="Box Wholesale Base Price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="box_wholesale_min_price",
            field=models.FloatField(
                default=0.0, verbose_name="Box Wholesale Min Price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="case_base_price",
            field=models.FloatField(default=0.0, verbose_name="Case Base Price"),
        ),
        migrations.AddField(
            model_name="product",
            name="case_cost_price",
            field=models.FloatField(default=0.0, verbose_name="Case Cost Price"),
        ),
        migrations.AddField(
            model_name="product",
            name="case_retail_base_price",
            field=models.FloatField(default=0.0, verbose_name="Case Retail Base Price"),
        ),
        migrations.AddField(
            model_name="product",
            name="case_retail_min_price",
            field=models.FloatField(default=0.0, verbose_name="Case Retail Min Price"),
        ),
        migrations.AddField(
            model_name="product",
            name="case_upc",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Case UPC"),
        ),
        migrations.AddField(
            model_name="product",
            name="case_wholesale_base_price",
            field=models.FloatField(
                default=0.0, verbose_name="Case Wholesale Base Price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="case_wholesale_min_price",
            field=models.FloatField(
                default=0.0, verbose_name="Case Wholesale Min Price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="piece_base_price",
            field=models.FloatField(default=0.0, verbose_name="Piece Base Price"),
        ),
        migrations.AddField(
            model_name="product",
            name="piece_cost_price",
            field=models.FloatField(default=0.0, verbose_name=" Piece Cost Price"),
        ),
        migrations.AddField(
            model_name="product",
            name="piece_retail_base_price",
            field=models.FloatField(
                default=0.0, verbose_name="Piece Retail Base Price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="piece_retail_min_price",
            field=models.FloatField(default=0.0, verbose_name="Piece Retail Min Price"),
        ),
        migrations.AddField(
            model_name="product",
            name="piece_wholesale_base_price",
            field=models.FloatField(
                default=0.0, verbose_name="Piece Wholesale Base Price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="piece_wholesale_min_price",
            field=models.FloatField(
                default=0.0, verbose_name="Piece Wholesale Min Price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_upc",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Product UPC"),
        ),
    ]
