# Generated by Django 4.1.7 on 2023-07-05 10:04

import app_modules.customers.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rename_piece_base_price_product_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('barcode_number', models.IntegerField()),
                ('barcode_code', models.FileField(upload_to='product/barcode', validators=[app_modules.customers.validators.validate_file_extension])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_barcode', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
