# Generated by Django 4.1.7 on 2023-07-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='product_type',
            field=models.CharField(default=1, max_length=10, verbose_name='Product Type'),
            preserve_default=False,
        ),
    ]
