# Generated by Django 4.1.7 on 2023-07-05 12:38

import app_modules.customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_barcode_barcode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode_code',
            field=models.FileField(upload_to='product-barcode', validators=[app_modules.customers.validators.validate_file_extension]),
        ),
    ]
