# Generated by Django 4.1.7 on 2023-07-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_barcode_barcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
