# Generated by Django 4.1.7 on 2023-07-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_barcode_barcode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
