# Generated by Django 4.1.7 on 2023-06-30 11:19

import app_modules.purchase_order.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_alter_product_box_piece_alter_product_case_piece_and_more'),
        ('company', '0008_remove_warehouse_address1_remove_warehouse_address2_and_more'),
        ('vendors', '0005_rename_address2_vendor_address_line_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('bill_number', models.PositiveIntegerField(max_length=50, verbose_name='Bill No')),
                ('bill_date', models.DateField(verbose_name='Bill Date')),
                ('remarks', models.CharField(max_length=100, verbose_name='Remarks')),
                ('total_price', models.FloatField(default=0.0, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('reverted', 'Reverted'), ('pending', 'Pending')], default='pending', max_length=10, verbose_name='Status')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='purchase-order-invoice', validators=[app_modules.purchase_order.validators.validate_invoice_file_extension], verbose_name='Purchase Order Invoice')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_purchase_order', to='company.company', verbose_name='Company')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_purchase_order', to='vendors.vendor', verbose_name='Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('unit_type', models.CharField(max_length=10, verbose_name='Unit Type')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('cost_price', models.FloatField(default=0.0, verbose_name='Cost Price')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_purchase_order', to='product.product')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_products', to='purchase_order.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
