# Generated by Django 4.1.7 on 2023-07-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_number',
            field=models.PositiveIntegerField(verbose_name='Bill No'),
        ),
    ]
