# Generated by Django 4.1.7 on 2023-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_purchaseorderproducts_total_pieces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproducts',
            name='total_pieces',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Pieces'),
        ),
    ]
