# Generated by Django 4.1.7 on 2023-07-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_alter_purchaseorderproducts_total_pieces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_number',
            field=models.CharField(max_length=100, verbose_name='Bill No'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproducts',
            name='unit_type',
            field=models.CharField(max_length=50, verbose_name='Unit Type'),
        ),
    ]
