# Generated by Django 4.1.7 on 2023-06-29 06:22

import app_modules.customers.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_remove_warehouse_address1_remove_warehouse_address2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('customer_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('customer_type', models.CharField(choices=[('distributor', 'Distributor'), ('retail', 'Retail'), ('wholesale', 'Wholesale')], max_length=20, verbose_name='Customer Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, verbose_name='Status')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tax Id')),
                ('terms', models.CharField(choices=[('case', 'Case'), ('check', 'Check'), ('net 10', 'Net 10'), ('net 15', 'Net 15'), ('net 30', 'Net 30')], max_length=20, verbose_name='Terms')),
                ('dba_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='DBA Name')),
                ('document', models.FileField(upload_to='customer documents', validators=[app_modules.customers.validators.validate_file_extension])),
                ('store_open_time', models.TimeField(verbose_name='Store Open Time')),
                ('store_close_time', models.TimeField(verbose_name='Store Close Time')),
                ('billing_address_line_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 1')),
                ('billing_address_line_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 2')),
                ('billing_suite_apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Suite/Apartment')),
                ('billing_zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('billing_state', models.CharField(blank=True, max_length=20, null=True, verbose_name='State')),
                ('billing_city', models.CharField(blank=True, max_length=20, null=True, verbose_name='City')),
                ('billing_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('billing_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('shipping_address_line_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 1')),
                ('shipping_address_line_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 2')),
                ('shipping_suite_apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Suite/Apartment')),
                ('shipping_zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('shipping_state', models.CharField(blank=True, max_length=20, null=True, verbose_name='State')),
                ('shipping_city', models.CharField(blank=True, max_length=20, null=True, verbose_name='City')),
                ('shipping_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('shipping_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('customer_type', models.CharField(choices=[('distributor', 'Distributor'), ('retail', 'Retail'), ('wholesale', 'Wholesale')], max_length=20, verbose_name='Customer Type')),
                ('price_level', models.CharField(max_length=30, verbose_name='Price Level Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('route_name', models.CharField(max_length=50, verbose_name='Route Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, verbose_name='Status')),
                ('customer', models.ManyToManyField(blank=True, null=True, related_name='salesroute_customer', to='customers.customer')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('receive_date', models.DateField(default=datetime.date.today, verbose_name='Receive Date')),
                ('entry_date', models.DateField(default=datetime.date.today, verbose_name='Entry Date')),
                ('receive_amount', models.FloatField(default=0.0, verbose_name='Receive Amount')),
                ('payment_mode', models.CharField(choices=[('check', 'Check'), ('case', 'Case'), ('credit card', 'Credit Card'), ('money order', 'Money Order'), ('electronic transfer', 'Electronic Transfer')], max_length=30, verbose_name='Payment Mode')),
                ('check_no', models.IntegerField(blank=True, null=True, verbose_name='Check No')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='Reference Id')),
                ('remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='Remark')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_customer', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('type', models.CharField(choices=[('store', 'Store'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20, verbose_name='Type')),
                ('contact_person', models.CharField(max_length=30, verbose_name='Contact Person')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile No')),
                ('is_default', models.BooleanField(default=False, verbose_name='is Default')),
                ('customer_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
