# Generated by Django 4.1.7 on 2023-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Country'),
        ),
    ]
