# Generated by Django 4.1.7 on 2023-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_billing_country_customer_shipping_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('check', 'Check'), ('cash', 'Cash'), ('credit card', 'Credit Card'), ('money order', 'Money Order'), ('electronic transfer', 'Electronic Transfer')], max_length=30, verbose_name='Payment Mode'),
        ),
    ]
