# Generated by Django 4.1.7 on 2023-06-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_box_piece_alter_product_case_piece_and_more'),
        ('customers', '0003_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLevelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('custom_price', models.PositiveIntegerField(verbose_name='Customer')),
                ('price_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelevel', to='customers.pricelevel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
