# Generated by Django 4.1.7 on 2023-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_pricelevelproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelevelproduct',
            name='unit_type',
            field=models.CharField(choices=[('box', 'Box'), ('case', 'Case'), ('piece', 'Piece')], default='piece', max_length=7, verbose_name='Unit Type'),
        ),
        migrations.AlterField(
            model_name='pricelevelproduct',
            name='custom_price',
            field=models.PositiveIntegerField(verbose_name='Custom Price'),
        ),
    ]
