# Generated by Django 4.1.7 on 2023-07-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_warehouse_address1_remove_warehouse_address2_and_more'),
        ('customers', '0005_pricelevelproduct_unit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelevel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_pricelevel', to='company.company'),
        ),
    ]
