# Generated by Django 4.1.7 on 2023-07-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_created_at_alter_customer_updated_at_and_more'),
        ('customers', '0006_pricelevel_company'),
    ]

    operations = [
    ]
