# Generated by Django 4.1.7 on 2023-06-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="address1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address2",
            field=models.CharField(max_length=100),
        ),
    ]
