# Generated by Django 4.1.7 on 2023-06-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_alter_vendor_address1_alter_vendor_address2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="address2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
