# Generated by Django 4.1.7 on 2023-06-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_vendor_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="address2",
            new_name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="address1",
        ),
        migrations.AddField(
            model_name="vendor",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
