# Generated by Django 4.1.7 on 2023-07-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0006_alter_vendor_created_at_alter_vendor_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="office_number_1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="office_number_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="zip_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
