# Generated by Django 4.1.7 on 2023-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_warehouse_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='address1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address2',
            field=models.CharField(max_length=150),
        ),
    ]
