# Generated by Django 4.1.7 on 2023-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_warehouse_address1_alter_warehouse_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(max_length=50, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address1',
            field=models.CharField(max_length=150, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address2',
            field=models.CharField(max_length=150, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='latitude',
            field=models.CharField(max_length=50, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='longitude',
            field=models.CharField(max_length=50, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='zip_code',
            field=models.IntegerField(verbose_name='Zip Code'),
        ),
    ]
