# Generated by Django 4.1.7 on 2023-06-26 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0006_companyusers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyusers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Company",
            ),
        ),
    ]
