# Generated by Django 4.1.7 on 2023-06-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_alter_companyusers_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="address1",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="address2",
        ),
        migrations.AddField(
            model_name="warehouse",
            name="address_line_1",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Address Line 1"
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Address Line 2"
            ),
        ),
    ]
