# Generated by Django 4.1.7 on 2023-07-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_alter_company_created_at_alter_company_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="latitude",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="longitude",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="state",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="zip_code",
            field=models.IntegerField(blank=True, null=True, verbose_name="Zip Code"),
        ),
    ]
